# Generated by Django 4.1.7 on 2023-03-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainImages',
            fields=[
                ('TrainImageId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=255)),
                ('classImages', models.ManyToManyField(to='ML_API.imagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PredictImages',
            fields=[
                ('TrainImageId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=255)),
                ('classImages', models.ManyToManyField(to='ML_API.imagemodel')),
            ],
        ),
    ]
