# Generated by Django 4.1.7 on 2023-03-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML_API', '0002_rename_trainimageid_predictimages_predictimageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictimages',
            name='classImages',
            field=models.ManyToManyField(blank=True, null=True, to='ML_API.imagemodel'),
        ),
        migrations.AlterField(
            model_name='trainimages',
            name='classImages',
            field=models.ManyToManyField(blank=True, null=True, to='ML_API.imagemodel'),
        ),
    ]
